name: Release Go Binary

on:
  release:
    types: [published]

jobs:
  build_and_release_ubuntu:
    runs-on: ubuntu-latest # Or another suitable runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4' # Specify your desired Go version

    - name: Build Go binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o amnezia-xray-to-vless-url ./cmd/amnezia_xray_to_vless_url

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          amnezia-xray-to-vless-url
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}